/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oI7ufjAKxTf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from '@/shared/ui/avatar'
import { Button } from '@/shared/ui/button'
import {
    DropdownMenu,
    DropdownMenuTrigger,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
} from '@/shared/ui/dropdown-menu'
import { Input } from '@/shared/ui/input'

export function Component() {
    return (
        <div className='flex h-screen w-full'>
            <div className='bg-background border-r border-muted flex flex-col gap-4 p-4 w-60'>
                <div className='flex items-center gap-2'>
                    <MailIcon className='w-6 h-6 text-primary' />
                    <h1 className='text-xl font-bold'>HR Hub</h1>
                </div>
                <nav className='flex flex-col gap-2'>
                    <Button
                        variant='ghost'
                        className='justify-start gap-2 w-full'>
                        <InboxIcon className='w-4 h-4' />
                        Inbox
                        <div className='ml-auto flex h-5 w-5 items-center justify-center rounded-full bg-primary text-primary-foreground text-xs font-medium'>
                            3
                        </div>
                    </Button>
                    <Button
                        variant='ghost'
                        className='justify-start gap-2 w-full'>
                        <CalendarIcon className='w-4 h-4' />
                        Calendar
                    </Button>
                    <Button
                        variant='ghost'
                        className='justify-start gap-2 w-full'>
                        <UsersIcon className='w-4 h-4' />
                        Employees
                    </Button>
                    <Button
                        variant='ghost'
                        className='justify-start gap-2 w-full'>
                        <SettingsIcon className='w-4 h-4' />
                        Settings
                    </Button>
                </nav>
                <div className='bg-card rounded-md shadow-sm p-4 flex flex-col gap-4'>
                    <div className='flex items-center gap-4'>
                        <Avatar className='w-10 h-10 border'>
                            <AvatarImage src='/placeholder-user.jpg' />
                            <AvatarFallback>HR</AvatarFallback>
                        </Avatar>
                        <div>
                            <div className='font-medium'>HR Specialist</div>
                            <div className='text-muted-foreground text-sm'>
                                Jane Doe
                            </div>
                        </div>
                    </div>
                    <Button variant='outline' className='w-full'>
                        Logout
                    </Button>
                </div>
            </div>
            <div className='flex-1 flex flex-col'>
                <header className='bg-background border-b border-muted flex items-center gap-4 px-6 h-16'>
                    <div className='relative flex-1'>
                        <SearchIcon className='absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground' />
                        <Input
                            type='search'
                            placeholder='Search messages...'
                            className='pl-10 w-full'
                        />
                    </div>
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button
                                variant='ghost'
                                size='icon'
                                className='rounded-full'>
                                <FilterIcon className='w-4 h-4' />
                                <span className='sr-only'>Filter</span>
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align='end'>
                            <DropdownMenuItem>
                                <InboxIcon className='w-4 h-4 mr-2' />
                                Inbox
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                                <CalendarIcon className='w-4 h-4 mr-2' />
                                Calendar
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                                <UsersIcon className='w-4 h-4 mr-2' />
                                Employees
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem>
                                <FilterIcon className='w-4 h-4 mr-2' />
                                Filter
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button
                                variant='ghost'
                                size='icon'
                                className='rounded-full'>
                                <ListOrderedIcon className='w-4 h-4' />
                                <span className='sr-only'>Sort</span>
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align='end'>
                            <DropdownMenuItem>
                                <UsersIcon className='w-4 h-4 mr-2' />
                                Newest
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                                <HistoryIcon className='w-4 h-4 mr-2' />
                                Oldest
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                                <BookMinusIcon className='w-4 h-4 mr-2' />
                                Unread
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </header>
                <div className='flex-1 overflow-auto'>
                    <div className='grid gap-4 p-6'>
                        <div className='bg-card rounded-md shadow-sm relative'>
                            <div className='flex items-start gap-4 p-4'>
                                <Avatar className='w-10 h-10 border'>
                                    <AvatarImage src='/placeholder-user.jpg' />
                                    <AvatarFallback>JD</AvatarFallback>
                                </Avatar>
                                <div className='flex-1'>
                                    <div className='flex items-center justify-between'>
                                        <div className='font-medium'>
                                            John Doe
                                        </div>
                                        <div className='text-xs text-muted-foreground'>
                                            2 hours ago
                                        </div>
                                    </div>
                                    <p className='text-muted-foreground'>
                                        Hi there, I wanted to follow up on the
                                        HR policy changes we discussed last
                                        week. Can we schedule a quick call to go
                                        over the details?
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div className='bg-card rounded-md shadow-sm'>
                            <div className='flex items-start gap-4 p-4'>
                                <Avatar className='w-10 h-10 border'>
                                    <AvatarImage src='/placeholder-user.jpg' />
                                    <AvatarFallback>SA</AvatarFallback>
                                </Avatar>
                                <div className='flex-1'>
                                    <div className='flex items-center justify-between'>
                                        <div className='font-medium'>
                                            Sarah Adams
                                        </div>
                                        <div className='text-xs text-muted-foreground'>
                                            1 day ago
                                        </div>
                                    </div>
                                    <p className='text-muted-foreground'>
                                        I wanted to discuss the new employee
                                        onboarding process. Can we set up a
                                        meeting to go over the changes?
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div className='bg-card rounded-md shadow-sm'>
                            <div className='flex items-start gap-4 p-4'>
                                <Avatar className='w-10 h-10 border'>
                                    <AvatarImage src='/placeholder-user.jpg' />
                                    <AvatarFallback>MJ</AvatarFallback>
                                </Avatar>
                                <div className='flex-1'>
                                    <div className='flex items-center justify-between'>
                                        <div className='font-medium'>
                                            Michael Johnson
                                        </div>
                                        <div className='text-xs text-muted-foreground'>
                                            3 days ago
                                        </div>
                                    </div>
                                    <p className='text-muted-foreground'>
                                        I have a question about the new health
                                        insurance plan. Can you please provide
                                        more details?
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div className='bg-card rounded-md shadow-sm relative'>
                            <div className='flex items-start gap-4 p-4'>
                                <Avatar className='w-10 h-10 border'>
                                    <AvatarImage src='/placeholder-user.jpg' />
                                    <AvatarFallback>EM</AvatarFallback>
                                </Avatar>
                                <div className='flex-1'>
                                    <div className='flex items-center justify-between'>
                                        <div className='font-medium'>
                                            Emily Martinez
                                        </div>
                                        <div className='text-xs text-muted-foreground'>
                                            1 week ago
                                        </div>
                                    </div>
                                    <p className='text-muted-foreground'>
                                        I wanted to discuss the new employee
                                        referral program. Can we set up a time
                                        to chat?
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

function BookMinusIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
            <path d='M9 10h6' />
        </svg>
    )
}

function CalendarIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <path d='M8 2v4' />
            <path d='M16 2v4' />
            <rect width='18' height='18' x='3' y='4' rx='2' />
            <path d='M3 10h18' />
        </svg>
    )
}

function FilterIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <polygon points='22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3' />
        </svg>
    )
}

function HistoryIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <path d='M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8' />
            <path d='M3 3v5h5' />
            <path d='M12 7v5l4 2' />
        </svg>
    )
}

function InboxIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <polyline points='22 12 16 12 14 15 10 15 8 12 2 12' />
            <path d='M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z' />
        </svg>
    )
}

function ListOrderedIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <line x1='10' x2='21' y1='6' y2='6' />
            <line x1='10' x2='21' y1='12' y2='12' />
            <line x1='10' x2='21' y1='18' y2='18' />
            <path d='M4 6h1v4' />
            <path d='M4 10h2' />
            <path d='M6 18H4c0-1 2-2 2-3s-1-1.5-2-1' />
        </svg>
    )
}

function MailIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <rect width='20' height='16' x='2' y='4' rx='2' />
            <path d='m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7' />
        </svg>
    )
}

function SearchIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <circle cx='11' cy='11' r='8' />
            <path d='m21 21-4.3-4.3' />
        </svg>
    )
}

function SettingsIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <path d='M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z' />
            <circle cx='12' cy='12' r='3' />
        </svg>
    )
}

function UsersIcon(props) {
    return (
        <svg
            {...props}
            xmlns='http://www.w3.org/2000/svg'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            stroke='currentColor'
            strokeWidth='2'
            strokeLinecap='round'
            strokeLinejoin='round'>
            <path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2' />
            <circle cx='9' cy='7' r='4' />
            <path d='M22 21v-2a4 4 0 0 0-3-3.87' />
            <path d='M16 3.13a4 4 0 0 1 0 7.75' />
        </svg>
    )
}
