name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-node-app:${{ github.sha }}

            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-node-app:${{ github.sha }}
                      docker stop my-node-app || true
                      docker rm my-node-app || true
                      docker run -d --name my-node-app -p 6666:6666 ${{ secrets.DOCKER_HUB_USERNAME }}/my-node-app:${{ github.sha }}
